---
- hosts: all
  become: yes
  tasks:
    - name: install webserver on ubuntu sarver
      apt:
       name: "{{mywebsarverforubuntu}}"
       state: present 
       when: ansible_os_family=="Debian"